version: "3.7"

networks:
    backend:
    frontend:

secrets:
    db_root_password:
        file: secrets/db_root_password
        # external: true
    db_user:
        file: secrets/db_user
        # external: true
    db_password:
        file: secrets/db_password
        # external: true
    db_backup_user:
        file: secrets/db_backup_user
        # external: true
    db_backup_password:
        file: secrets/db_backup_password
        # external: true
    restic_password:
        file: secrets/restic_password
        # external: true
    STAGE_B2_ACCOUNT_ID:
        file: secrets/STAGE_B2_ACCOUNT_ID
        # external: true
    STAGE_B2_ACCOUNT_KEY:
        file: secrets/STAGE_B2_ACCOUNT_KEY
        # external: true


services:
    mariadb:
        image: "markdumay/mariadb:latest"
        hostname: mariadb
        command: --max_allowed_packet=256M
        restart: unless-stopped
        networks:
            - backend
        volumes:
            # make mariadb database data, backups, and logs persistent
            - ./data/mariadb/mysql:/var/lib/mysql
            - ./data/mariadb/backup:/var/backup/mariadb
            - ./data/mariadb/log:/var/log
            # cross-reference Ghost images, logs, settings, and themes for remote backup
            - ./data/ghost:/var/backup/ghost
            # add folder with initialization script to create backup database user and password
            - ./config/mariadb/init:/docker-entrypoint-initdb.d:ro
        environment:
            # database settings
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
            - MYSQL_USER_FILE=/run/secrets/db_user
            - MYSQL_PASSWORD_FILE=/run/secrets/db_password
            # backup settings
            - BACKUP=${BACKUP}
            - RESTIC_REPOSITORY=${RESTIC_REPOSITORY}
            - RESTIC_PASSWORD_FILE=/run/secrets/restic_password
        secrets:
            - db_root_password
            - db_user
            - db_password
            - db_backup_user
            - db_backup_password
            - restic_password
            - STAGE_B2_ACCOUNT_ID
            - STAGE_B2_ACCOUNT_KEY
        

    # https://hub.docker.com/_/ghost/
    ghost:
        image: "markdumay/ghost:latest"
        restart: unless-stopped
        links:
            - mariadb
        networks:
            - backend
            - frontend
        ports:
            - 2368:2368
        volumes:
            # make Ghost images, logs, settings, and themes persistent
            - ./data/ghost:/var/lib/ghost/content
            # add support for Docker secrets
            - ./config/ghost/db/connection.js:/var/lib/ghost/current/core/server/data/db/connection.js:ro
        environment:
            # core ghost settings
            - url=http://${DOMAINS_BLOG}
            - admin=http://${DOMAINS_ADMIN}
            - database__client=mysql
            - database__connection__host=mariadb
            - database__connection__database=${DB_NAME}
            - database__connection__user__file=/run/secrets/db_user
            - database__connection__password__file=/run/secrets/db_password
            # boot dependencies
            - WAIT_HOSTS=mariadb:3306
            - WAIT_SLEEP_INTERVAL=5
            - WAIT_HOSTS_TIMEOUT=300            
            # indicate wether the default Ghost theme (Casper) should be installed
            - THEMES=${THEMES}
            # notification settings
            # - mail__transport: SMTP
            # - mail__from: "Server <${ACME_EMAIL}>"
            # - mail__options__service: SMTP
            # - mail__options__host: mail
            # - mail__options__port: 25
        secrets:
            - db_user
            - db_password

    # TODO: add admin url
    portal:
        image: "markdumay/portal:latest"
        ports:
            - 80:80
            - 443:443
        links:
            - ghost
        restart: unless-stopped
        networks:
            frontend:
        volumes:
            # make Portal data persistent
            - ./data/portal:/var/lib/https-portal
            # cross-reference Ghost images and themes for caching
            - ./data/ghost:/var/lib/ghost/content:ro
        environment:
            - DOMAINS=
              ${DOMAINS_BLOG} -> ${GHOST_HOST},
              www.${DOMAINS_BLOG} => https://${DOMAINS_BLOG},
              ${DOMAINS_ADMIN} => https://${DOMAINS_BLOG}/ghost/
            - STAGE=${STAGE}
            - CACHING=${CACHING}
            - DOMAINS_BLOG=${DOMAINS_BLOG}

    # TODO: add mail or slack support

    # https://hub.docker.com/r/bytemark/smtp
    # mail:
    #     image: bytemark/smtp
    #     restart: unless-stopped
    #     networks:
    #         - frontend