secrets:
  db_root_password:
    file: secrets/db_root_password
    external: false
  db_user:
    file: secrets/db_user
    external: false
  db_password:
    file: secrets/db_password
    external: false
  db_backup_user:
    file: secrets/db_backup_user
    external: false
  db_backup_password:
    file: secrets/db_backup_password
    external: false

services:
  mariadb:
    build:
      dockerfile: ./config/mariadb/docker/Dockerfile
      context: .
      args:
        BUILD_VERSION: "${BUILD_VERSION}"
        BUILD_UID: "${BUILD_UID}"
        BUILD_GID: "${BUILD_GID}"
        BUILD_FLAGS: --add-shell
        BUILD_TARGET: test
        MARIADB_VERSION: "${MARIADB_VERSION}"
        MARIADB_ALPINE_VERSION: "${MARIADB_ALPINE_VERSION}"

  ghost:
    build:
      dockerfile: ./config/ghost/docker/Dockerfile
      context: .
      args:
        BUILD_VERSION: "${BUILD_VERSION}"
        BUILD_UID: "${BUILD_UID}"
        BUILD_GID: "${BUILD_GID}"
        BUILD_FLAGS: --add-shell
        BUILD_TARGET: test
        GHOST_VERSION: "${GHOST_VERSION}"
        GHOST_CLI_VERSION: "${GHOST_CLI_VERSION}"
        WAIT_VERSION: "${WAIT_VERSION}"
        NODE_MAJOR_VERSION: "${NODE_MAJOR_VERSION}"
        GHOST_ALPINE_VERSION: "${GHOST_ALPINE_VERSION}"