secrets:
    db_root_password:
        file: secrets/db_root_password
        external: false
    db_user:
        file: secrets/db_user
        external: false
    db_password:
        file: secrets/db_password
        external: false
    db_backup_user:
        file: secrets/db_backup_user
        external: false
    db_backup_password:
        file: secrets/db_backup_password
        external: false
    restic_password:
        file: secrets/restic_password
        external: false
    STAGE_B2_ACCOUNT_ID:
        file: secrets/STAGE_B2_ACCOUNT_ID
        external: false
    STAGE_B2_ACCOUNT_KEY:
        file: secrets/STAGE_B2_ACCOUNT_KEY
        external: false


services:
    mariadb:
        build:
            dockerfile: docker/Dockerfile
            context: ./config/mariadb
       
    ghost:
        build:
            dockerfile: Dockerfile
            context: ./config/ghost/docker