version: "3.7"

networks:
    backend:
    frontend:

secrets:
    db_root_password:
        file: secrets/db_root_password
        # external: true
    db_user:
        file: secrets/db_user
        # external: true
    db_password:
        file: secrets/db_password
        # external: true
    db_backup_user:
        file: secrets/db_backup_user
        # external: true
    db_backup_password:
        file: secrets/db_backup_password
        # external: true


services:
    # TODO: add backup script
    mariadb:
        # image: mariadb:10.3
        build:
            context: .
            dockerfile: Dockerfile_mariadb
        hostname: mariadb
        command: --max_allowed_packet=256M
        restart: unless-stopped
        networks:
            - backend
        volumes:
            # make mariadb data persistent
            - ./data/mariadb:/var/lib/mysql
            # add folder with initialization script to create backup database user and password
            - ./config/mariadb/init:/docker-entrypoint-initdb.d:ro
            # # Add Docker entrypoint script
            # - ./config/mariadb/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint-override.sh:ro
            # # Add cron jobs
            # - ./config/mariadb/cron/backup_full.sh:/usr/local/bin/backup_full.sh:ro
            # - ./config/mariadb/cron/backup_inc.sh:/usr/local/bin/backup_inc.sh:ro
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
            - MYSQL_USER_FILE=/run/secrets/db_user
            - MYSQL_PASSWORD_FILE=/run/secrets/db_password
            - BACKUP=$BACKUP
        secrets:
            - db_root_password
            - db_user
            - db_password
            - db_backup_user
            - db_backup_password


    # https://hub.docker.com/_/ghost/
    ghost:
        # TODO: replace with hub image
        # image: ghost:3-alpine
        build:
            context: .
            dockerfile: Dockerfile_ghost
        restart: unless-stopped
        links:
            - mariadb
        networks:
            - backend
            - frontend
        ports:
            - 2368:2368
        volumes:
            - ./data/ghost:/var/lib/ghost/content
            # Add support for Docker secrets
            - ./config/ghost/db/connection.js:/var/lib/ghost/current/core/server/data/db/connection.js:ro
        environment:
            - WAIT_HOSTS=mariadb:3306
            - WAIT_SLEEP_INTERVAL=5
            - WAIT_HOSTS_TIMEOUT=300            
            - url=http://${DOMAINS_BLOG}
            - admin=http://${DOMAINS_ADMIN}
            - database__client=mysql
            - database__connection__host=mariadb
            - database__connection__database=${DB_NAME}
            - database__connection__user__file=/run/secrets/db_user
            - database__connection__password__file=/run/secrets/db_password
            - THEMES=$THEMES
            # - mail__transport: SMTP
            # - mail__from: "Server <${ACME_EMAIL}>"
            # - mail__options__service: SMTP
            # - mail__options__host: mail
            # - mail__options__port: 25
        secrets:
            - db_user
            - db_password

    # TODO: add mail or slack support

    # https://hub.docker.com/r/bytemark/smtp
    # mail:
    #     image: bytemark/smtp
    #     restart: unless-stopped
    #     networks:
    #         - frontend

    # TODO: add portal
    # https-portal:
    #     image: steveltn/https-portal:1
    #     ports:
    #         - 80:80
    #         - 443:443
    #     links:
    #         - ghost
    #     restart: always
    #     networks:
    #         - frontend
    #     volumes:
    #         - ./https-portal:/var/lib/https-portal
    #     environment:
    #         DOMAINS: '${DOMAINS_GHOST} -> http://ghost:2368, ${DOMAINS_MATOMO} -> http://matomo'
    #         # STAGE: 'production'

